### ISSUE TITLE
Manual Deploy to Production: Double or triple check that production is the remote we want

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-wp#10]
To avoid accidental deploys to Production in our manual script, let's put a "are you sure you want to push to production?" confirmation. I believe it's a `wait` in bash (?).

**Comment by ccorda** [comment]
@kylehotchkiss you already have to run `build.sh production`. If you don't specify `production` or `staging`, then the script completes with a failure notice:

https://github.com/patronage/bubs-wp/blob/master/_build/deploy.sh#L94

Feels sufficient enough to me.
