### ISSUE TITLE
database provisioning

### ISSUE THREAD

**Issue by imjared** [patronage/bubs-wp#23]
Does Bubs require using WP Engine? There's no starter DB to import and unlike the "famous 5 minute install", it doesn't seem like we provision one.

We should either include some starter SQL or explain how to get the DB working

related to #17

**Comment by ccorda** [comment]
There are so few steps, that we tend to just just use the default WP database, and change the 2 or 3 things that need changing.

But these should be documented on wiki. Closing this, but adding to #17 as a thing that needs documenting.
