### ISSUE TITLE
Common ways of setting classes, js, css, and other things per page

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-wp#3]
I've seen some places where we use `body_class`, which overwrites things that WP needs to show admin bar.  Should have a common interface for this, and also for adding page specific JS, and maybe CSS.

- - - - - 

Just saw this in another commit, this is useful and we should add it.
`<body {{ function('body_class', body_classes ) }} id="{{ body_id }}">`

**Comment by ccorda** [comment]
Definitely useful, here is another case where we hardcode something in: `<body {{ function('body_class', " v3  " ~ body_class ~ " " ~ layout  ) }}>`.
