### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-wp#8]
WP has built in favicon support now.  we need to check to see if that is populated before we output our own code (or just remove our own):
https://github.com/patronage/bubs/blob/master/wp-content/themes/timber/views/layout.twig#L40

---

I'm trying to track this functionality down in the wiki - https://codex.wordpress.org/Creating_a_Favicon

hopefully I can find a favicon function

**Comment by ccorda** [comment]
@kylehotchkiss no need for a function, it just gets output via `{{ wp_head }}.

Output looks like this:

```
<link rel="icon" href="/wp-content/uploads/2016/12/cropped-patronage-logo512-32x32.png" sizes="32x32" />
<link rel="icon" href="/wp-content/uploads/2016/12/cropped-patronage-logo512-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="/wp-content/uploads/2016/12/cropped-patronage-logo512-180x180.png" />
<meta name="msapplication-TileImage" content="/wp-content/uploads/2016/12/cropped-patronage-logo512-270x270.png" />
```

Will remove our favicon code and close this out.

**Comment by kylehotchkiss** [comment]
Nice!
